#!/bin/sh

j=1
for i in '[[1,2,3,4],[5,6,7,8],[9,10,11,0],[13,14,15,12]]' '[[1,2,3,4],[5,6,7,8],[9,11,12,0],[13,10,14,15]]' '[[1,6,2,3],[5,8,7,4],[9,10,0,11],[13,14,15,12]]' '[[1,4,7,8],[6,2,0,3],[5,10,11,12],[9,13,14,15]]' '[[0,2,4,8],[1,3,7,6],[9,5,10,12],[13,14,11,15]]' '[[7,0,12,3],[1,5,4,8],[6,2,11,10],[9,13,14,15]]' '[[2,5,7,3],[1,0,9,8],[13,10,4,11],[14,15,6,12]]' '[[2,3,7,4],[5,14,0,8],[10,6,1,12],[9,13,15,11]]' '[[5,1,0,2],[6,12,3,8],[9,4,13,7],[11,10,14,15]]' '[[2,4,8,7],[3,5,12,15],[6,0,10,11],[9,13,1,14]]'; do

gprolog --entry-goal "[quebraCabeca],principal(profundidade,posicao,$i),halt" > "$1-profPos-$j"
gprolog --entry-goal "[quebraCabeca],principal(profundidade,manhattan,$i),halt" > "$1-profMan-$j"
gprolog --entry-goal "[quebraCabeca],principal(largura,posicao,$i),halt" > "$1-largPos-$j"
gprolog --entry-goal "[quebraCabeca],principal(largura,manhattan,$i),halt" > "$1-largMan-$j"
gprolog --entry-goal "[quebraCabeca],principal(escalada,posicao,$i),halt" > "$1-escPos-$j"
gprolog --entry-goal "[quebraCabeca],principal(escalada,manhattan,$i),halt" > "$1-escfMan-$j"
gprolog --entry-goal "[quebraCabeca],principal(beam,posicao,$i),halt" > "$1-beamPos-$j"
gprolog --entry-goal "[quebraCabeca],principal(beam,manhattan,$i),halt" > "$1-beamMan-$j"
gprolog --entry-goal "[quebraCabeca],principal(gradiente,posicao,$i),halt" > "$1-gradPos-$j"
gprolog --entry-goal "[quebraCabeca],principal(gradiente,manhattan,$i),halt" > "$1-gradMan-$j"
gprolog --entry-goal "[quebraCabeca],principal(aestrela,posicao,$i),halt" > "$1-aestPos-$j"
gprolog --entry-goal "[quebraCabeca],principal(aestrela,manhattan,$i),halt" > "$1-aestMan-$j"
j=$(($j+1))
done
